//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appMobi.AppMobiCloudServiceExtension.VisualStudioUserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eterprise.appmobi.com/", ConfigurationName="VisualStudioUserService.VisualStudioUserSoap")]
    public interface VisualStudioUserSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://eterprise.appmobi.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://eterprise.appmobi.com/HelloWorld", ReplyAction="*")]
        appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse HelloWorld(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eterprise.appmobi.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse> HelloWorldAsync(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://eterprise.appmobi.com/", Order=0)]
        public appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://eterprise.appmobi.com/", Order=0)]
        public appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eterprise.appmobi.com/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VisualStudioUserSoapChannel : appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisualStudioUserSoapClient : System.ServiceModel.ClientBase<appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap>, appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap {
        
        public VisualStudioUserSoapClient() {
        }
        
        public VisualStudioUserSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisualStudioUserSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualStudioUserSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisualStudioUserSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap.HelloWorld(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest inValue = new appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest();
            inValue.Body = new appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequestBody();
            appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse retVal = ((appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse> appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap.HelloWorldAsync(appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldResponse> HelloWorldAsync() {
            appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest inValue = new appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequest();
            inValue.Body = new appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.HelloWorldRequestBody();
            return ((appMobi.AppMobiCloudServiceExtension.VisualStudioUserService.VisualStudioUserSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
